export const ROUTE_URLS = {
  DASHBAORD: 'dashboard',
  LOGIN: 'login',
  ADMIN: 'admin',
  ADD: 'add',
  EDIT: 'edit',
  DELETE: 'delete',
  ALL: 'all',
  PENDING: 'pending',
  LOGOUT: 'logout',
  HOMEPAGE: 'homepage',
  ALL_POSTS: 'all-posts',
  FRUIT_LIST: 'fruit-list',
  VEGETABLE_LIST: 'vegetable-list',
  CEREALS_LIST: 'cereals-list',
  SALT_LIST: 'salt-list',
  OIL_LIST: 'oil-list',
  SUGER_LIST: 'suger-list',

};
